version: '2'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
  frontend:
    build: ./frontend/.
    volumes:
      - ./frontend/.:/frontend
    ports:
      - "8888:8888"
